preload = /home/josh/Pictures/wallpaper_two.jpg
splash = false;
wallpaper {
    monitor =HDMI-A-2 
    path = /home/josh/Pictures/wallpaper_two.jpg
    fit_mode = cover
}

wallpaper {
    monitor =eDP-1 
    path = /home/josh/Pictures/wallpaper_two.jpg
    fit_mode = cover
}
wallpaper {
    monitor =DP-1 
    path = /home/josh/Pictures/wallpaper_two.jpg
    fit_mode = cover
}
